### ISSUE TITLE
Request all events

### ISSUE THREAD

**Issue by kde-work** [Cloudbet/schema#2]
Hi, I found in the code examples the query of upcoming events
```
$upcomingEvents = new \Sportsbook\EventList();
$upcomingEvents->parseFromString(getApiResponse('upcoming/' . $sportId));
```
Can I request all the events?

**Comment by kgravenreuth** [comment]
Hi kde-work,

there are several options for you to query more events, if you know the sport/comopetitions you could go over

    /sports/event_tree
    /sports/competition/:competition_id

and get a list of events from there. If you want "all" events per sport you could go over the asian API, see 

    /sports/asian_events/:sport_id

If you wan't "all" live events, you can go via

    /sports/live_events

Let me know if you need anything else.
