### ISSUE TITLE
Odds Feed not displaying

### ISSUE THREAD

**Issue by Pauline-Affiliates** [Cloudbet/schema#5]
Hi,

It seems our API is not working for affiliates, not displaying on Covers and other affiliates are reporting a 404.

REQUEST
GET /api/v2/sports HTTP/1.1
Host: api.cloudbet.com
Authorization: Bearer ********
User-Agent: Public API Client/1.0
Accept: application/json

RESPONSE
Status: 404 Not Found

**Comment by kgravenreuth** [comment]
Hi Pauline,

The path they are using is incorrect. The documentation for the API is here:

https://docs.cloudbet.com/

They should be using the /api/v1/sports end points rather than 'v2' end points.
