### ISSUE TITLE
Odds feed not working

### ISSUE THREAD

**Issue by Pauline-Affiliates** [Cloudbet/schema#7]
Hi,

I received the following from Covers:

"I'm contacting you on behalf of Covers.com.

We noticed that the odds for NBA and MLB are showing "off" on Covers site. On further investigation I noticed that the CloudBet feeds are down.

For NBA regular season:
https://api.cloudbet.com/api/v1/sports/competition/143
For MLB regular season:
https://api.cloudbet.com/api/v1/sports/competition/18

Can you please look into this matter and let us know when they are up or if you have any questions?"

Thanks

Pauline

**Comment by kgravenreuth** [comment]
Hi Pauline,
From our logs, we can see that they are able to reach our endpoints, including the Competition endpoint mentioned in this issue, https://api.cloudbet.com/api/v1/sports/competition/xxx

Furthermore, we can see Cloudbet odds available on covers.com For example, for MLB, the Cloudbet Odds are available at https://www.covers.com/Sports/MLB/Odds/INT/MONEYLINE/competition/Online/UK (also see attached site screenshot)

<img width="1367" alt="covers com_mlb_cloudbet_odds" src="https://user-images.githubusercontent.com/21211077/46846644-15c91400-ce13-11e8-80b5-6659e784cd7d.png">

Could you please request them to check the requested Cloudbet URLs again?
